general_configs : 
  sdk_session_id:
    dev: 0d0956ef32bc4ee8a08dc37e2552fe59
    uat: 0bef83f35cd94bdcb2eefef9b7d57e75
    prod: 64ec92d6117247877965d152
  tracking_env: dev
  tracking_url : mlcoredevv2pg21.azurewebsites.net

data_engineering_ft:
  datalake_configs:
    input_tables :
      source_1 : 
        catalog_name : null
        schema : diabetes_hive_db_v1
        table : diabetes_ft_v2
        primary_keys: index

    output_tables :
      output_1 :
        catalog_name : null
        schema : diabetes_hive_db_260701_v2
        table: diabetes_hive_ft_260701_v2
        primary_keys: index
  storage_configs:
    cloud_provider: azure
    params:
      storage_account_name: mlcdevtigerstorage38173
      container_name: mlcore
  is_scheduled : true
  batch_size : 500
  cron_job_schedule: 0 */30 * ? * *

data_engineering_gt:
  datalake_configs:
    input_tables :
      source_1 : 
        catalog_name : null
        schema : diabetes_hive_db_v1
        table : diabetes_gt_v2
        primary_keys: index
    output_tables :
      output_1 :
        catalog_name : null
        schema : diabetes_hive_db_260701_v2
        table: diabetes_hive_gt_260701_v2
        primary_keys: index
  storage_configs:
    cloud_provider: azure
    params:
      storage_account_name: mlcdevtigerstorage38173
      container_name: mlcore  
  is_scheduled : true
  batch_size : 500
  cron_job_schedule: 0 */30 * ? * *

feature_pipelines_ft:
  datalake_configs:
    input_tables :
      input_1 :
        catalog_name : null
        schema : diabetes_hive_db_260701_v2
        table: diabetes_hive_ft_260701_v2
        primary_keys: index
    output_tables :
        output_1 :
          catalog_name : null
          schema : diabetes_hive_db_260701_v2
          table: transformed_diabetes_hive_ft_260701_v2
          primary_keys: index
  storage_configs:
    cloud_provider: azure
    params:
      storage_account_name: mlcdevtigerstorage38173
      container_name: mlcore
  is_scheduled: false

feature_pipelines_gt:
  datalake_configs:
    input_tables : 
      input_1 :
        catalog_name : null
        schema : diabetes_hive_db_260701_v2
        table: diabetes_hive_gt_260701_v2
        primary_keys: index
    output_tables : 
        output_1 :
          catalog_name : null
          schema : diabetes_hive_db_260701_v2
          table: transformed_diabetes_hive_gt_260701_v2
          primary_keys: index  
  storage_configs:
    cloud_provider: azure
    params:
      storage_account_name: mlcdevtigerstorage38173
      container_name: mlcore
  is_scheduled: false

train:
  datalake_configs:
    input_tables : 
      input_1 :
        catalog_name : null
        schema : diabetes_hive_db_260701_v2
        table: transformed_diabetes_hive_ft_260701_v2
        primary_keys: index
      input_2 :
        catalog_name : null
        schema : diabetes_hive_db_260701_v2
        table: transformed_diabetes_hive_gt_260701_v2
        primary_keys: index
    output_tables : 
        output_1 :
          catalog_name : null
          schema : diabetes_hive_db_260701_v2
          table: trainoutput_diabetes_260701_v2
          primary_keys: index
  model_configs:
    registry_platform: databricks
    model_registry : mlflow
    unity_catalog : "no"
    model_registry_params:
      tracking_env: dev
      host_url: https://adb-1277783902121094.14.azuredatabricks.net
    model_params:   
      model_name: diabetes_260701_v2
  storage_configs:
    cloud_provider: azure
    params:
      storage_account_name: mlcdevtigerstorage38173
      container_name: mlcore
  test_size: 0.2
  feature_columns:
  - age
  - bmi
  - HbA1c_level
  - blood_glucose_level
  - gender_Male
  - hypertension_1
  - heart_disease_1
  - smoking_history_non-smoker
  - smoking_history_past_smoker
  target_columns:
  - diabetes
  is_scheduled: false
  hyperparameter_tuning:
    max_evaluations : 20
    primary_metric : accuracy
    search_range :
      fitIntercept : 
        - True
        - False
    max_evaluations : 20
    stop_early : false
    run_parallel : false

data_prep_deployment_ft:
  datalake_configs:
    input_tables :
      input_1 :
        catalog_name : null
        schema : diabetes_hive_db_260701_v2
        table: diabetes_hive_ft_260701_v2
        primary_keys: index
    output_tables :
        output_1 :
          catalog_name : null
          schema : diabetes_hive_db_260701_v2
          table: dpd_diabetes_ft_260701_v2
          primary_keys: index  
  storage_configs:
    cloud_provider: azure
    params:
      storage_account_name: mlcdevtigerstorage38173
      container_name: mlcore
  is_scheduled: true
  batch_size: 500
  cron_job_schedule: 0 */30 * ? * *

data_prep_deployment_gt:
  datalake_configs:
    input_tables :
      input_1 :
        catalog_name : null
        schema : diabetes_hive_db_260701_v2
        table: diabetes_hive_gt_260701_v2
        primary_keys: index
    output_tables : 
        output_1 :
          catalog_name : null
          schema : diabetes_hive_db_260701_v2
          table: dpd_diabetes_gt_260701_v2
          primary_keys: index  
  storage_configs:
    cloud_provider: azure
    params:
      storage_account_name: mlcdevtigerstorage38173
      container_name: mlcore
  is_scheduled: true
  batch_size: 500
  cron_job_schedule: 0 */30 * ? * *

inference:
  datalake_configs:
    input_tables : 
      input_1 :
        catalog_name : null
        schema : diabetes_hive_db_260701_v2
        table: dpd_diabetes_ft_260701_v2
        primary_keys: index
      input_2 :
        catalog_name : null
        schema : diabetes_hive_db_260701_v2
        table: dpd_diabetes_gt_260701_v2
        primary_keys: index
    output_tables : 
        output_1 :
          catalog_name : null
          schema : diabetes_hive_db_260701_v2
          table: inference_diabetes_260701_v2
          primary_keys: index
  is_scheduled: true
  batch_size: 100
  cron_job_schedule: 0 */30 * ? * *